### ISSUE TITLE
xiAnnotator input residue count should start with 0

### ISSUE THREAD

**Issue by colin-combe** [Rappsilber-Laboratory/xiUI#9] opened 2016-03-28 13:19 UTC
<a href="https://github.com/lutzfischer"><img src="https://avatars.githubusercontent.com/u/6330440?v=3" align="left" width="96" height="96" hspace="10"></img></a> **Issue by [lutzfischer](https://github.com/lutzfischer)**
_Friday Mar 25, 2016 at 13:41 GMT_
_Originally opened as https://github.com/colin-combe/CLMS-UI/issues/20_

---

xiAnnotator is currently called with the linkage-sites starting a 1 but it returns linkage-sites starting at 0. Needs to be unified.

**Comment by colin-combe** [comment] 2016-03-28 13:20
<a href="https://github.com/lutzfischer"><img src="https://avatars.githubusercontent.com/u/6330440?v=3" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [lutzfischer](https://github.com/lutzfischer)**
_Friday Mar 25, 2016 at 13:43 GMT_

----

The spectrum viewer currently expects the output also as starting with 0

**Comment by colin-combe** [comment] 2016-03-28 15:20
Recreating on correct project
https://github.com/Rappsilber-Laboratory/xiAnnotator/issues/1
closing

**Comment by lutzfischer** [comment] 2016-04-05 16:08
The issue is fixed in xiAnnotator - but needs to be addressed here now as well. xiAnnotator has now one more - optional - parameter:
firstresidue
Values for this parameter should be either 0 (what we would like to have) or 1 (what we have at the moment).
The parameter is defined with a default value of 1 - so it works correctly with the current way it is used.

**Closed** 2018-02-07 16:06 UTC
